CREATE TABLE CITY (
ID INT NOT NULL PRIMARY KEY,
NAME VARCHAR(255) not null
);

CREATE TABLE COUNTRY (
ID INT NOT NULL PRIMARY KEY,
NAME VARCHAR(255) not null
);

CREATE TABLE USER (
ID INT NOT NULL PRIMARY KEY,
FIRST_NAME VARCHAR(255) not null,
LAST_NAME VARCHAR(255) not null,
DEACTIVATED VARCHAR(255) null,
VERIFIED BOOLEAN null,
SEX INT null,
BDATE DATE null,
CITY INT null,
COUNTRY INT null,
HOME_TOWN VARCHAR(255) null,
PHOTO_ADDRESS VARCHAR(255) null,
STATUS VARCHAR(255) null,
FOLLOWERS_COUNT INT null,
RELATION INT null,
FRIENDS_NUM INT null,
MALE_FRIENDS INT null,
FEMALE_FRIENDS INT null,
FOLLOWERS INT null,
MALE_FOLLOWERS INT null,
FEMALE_FOLLOWERS INT null,
SUBSCRIPTIONS INT null,
GROUP_SUBSCRIPTIONS INT null,
MALE_SUBSCRIPTIONS INT null,
FEMALE_SUBSCRIPTIONS INT null,

FOREIGN KEY(CITY) REFERENCES CITY(ID),
FOREIGN KEY(COUNTRY) REFERENCES COUNTRY(ID)
);

CREATE TABLE USER_PHOTO (
ID INT NOT NULL PRIMARY KEY,
PHOTO BLOB null
)